path:
  JDapi: http://gturnquist-quoters.cfapps.io/api/random
  TBapi: http://gturnquist-quoters.cfapps.io/api/random
  JDlocal: /Users/xiaoxu/workspace/WORKSHOP-MAY/brand-server/src/main/resources/JDdata.json
  TBlocal: /Users/xiaoxu/workspace/WORKSHOP-MAY/brand-server/src/main/resources/TBdata.json
